export const GET_LOTS = "GET_LOTS";
export const SAVED_LOTS = "SAVED_LOTS";
export const LOT_ERROR = "LOT_ERROR";
export const LOTS_LOADING = "LOTS_LOADING";
export const SET_CURRENT_LOT = "SET_CURRENT_LOT";

export const GET_HOMEPLANS = "GET_HOMEPLANS";
export const SAVED_HOMEPLANS = "SAVED_HOMEPLANS";
export const HOMEPLAN_ERROR = "HOMEPLAN_ERROR";
export const HOMEPLANS_LOADING = "HOMEPLANS_LOADING";
export const SET_CURRENT_HOMEPLAN = "SET_CURRENT_HOMEPLAN";

export const GET_COMBINATIONS = "GET_COMBINATIONS";
export const COMBINATION_ERROR = "COMBINATION_ERROR";
export const COMBINATIONS_LOADING = "COMBINATIONS_LOADING";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
